PyDemo:
  cookies: null
  headers: func_header
  headers_admin: func_header{'user':'15800015001','pwd':'12345678'}
  header_befor: {'X-Lemonban-Media-Type': 'lemonban.v2'}
  admin_user: 15800015001
  admin_pwd: 12345678
  user_: 15808815004
  user_pwd: 12345678
  dbType: mysql
  # 环境和应用信息
  host: http://api.lemonban.com/futureloan
  # 可以自定义多个