# 运行项目名
project_name: PyDemo

# 运行模式:
auto_switch: 1
# 0 -不开启自动生成测试用例功能，将直接运行测试
# 1 -根据手工编写用例，自动生成测试脚本，然后运行测试
# 2 -根据接口抓包数据，自动生成测试用例和测试脚本，然后运行测试
# 3 -根据接口抓包数据，自动生成测试用例和测试脚本，但不运行测试
# 注意：目前解析仅支持(.chlsj)格式，请使用Charles工具抓包导出JSON Session File

# 扫描测试用例目录（且仅当auto_switch=1时有用） (会对没有写测试脚本的用例进行脚本重新)
scan_dir: ""

# 使用模糊匹配测试用例（空则匹配所有）
pattern: "MemberRegister"

# 执行并发线程数（0表示不开启）
process: 0

# 失败重试次数（0表示不重试）
reruns: 0

# 本轮测试最大允许失败数（超出则立即结束测试）
maxfail: 200

# 接口调用间隔时间（s）
interval: 1

# 跳过用例集  如：test_ContractCreateByCategory.yaml 此用例集 ，则在下方列表中写入 ["ContractCreateByCategory"] 可跳过多个 逗号分隔
skip: []

# jenkins地址
Jenkins_conf:
  url: http://192.168.60.190:8080/
  username: admin
  password: 'asdf1@34'
job_name: job/private_XM/

# 钉钉配置
dd_url: https://oapi.dingtalk.com/robot/send?access_token=46030407455f3f0c10bb186e041e470fc1c3c63c774582cd9775b41b66ee9760    #webhook

# 测试结果校验方式说明（共6种方式）：
# no_check：不做任何校验
# check_code：仅校验接口返回码code
# check_json：校验接口返回码code，并进行json格式比较返回结果（默认方式）
# entirely_check：校验接口返回码code，并进行完整比较返回结果
# regular_check：校验接口返回码code，并进行正则匹配返回结果
# check_db: 校验数据库